In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

+ Gender : 1 represents Male , 2 represents Female

+ Age Range : 1 represents >18 years of age , 2 represents <18 years of age

+ Head Size(cm^3)

+ Brain Weight(grams)

In [3]:
data = pd.read_csv("dataset.csv")
data

Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0         1          1             4512                 1530
1         1          1             3738                 1297
2         1          1             4261                 1335
3         1          1             3777                 1282
4         1          1             4177                 1590
..      ...        ...              ...                  ...
232       2          2             3214                 1110
233       2          2             3394                 1215
234       2          2             3233                 1104
235       2          2             3352                 1170
236       2          2             3391                 1120

[237 rows x 4 columns]

In [9]:
model = LinearRegression()
model.fit(data[['Gender', 'Age Range', 'Head Size(cm^3)']], data['Brain Weight(grams)'])

LinearRegression()

In [11]:
model.predict([[1,1,4177]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1438.1235879])

In [12]:
model.coef_

array([-22.5432537 , -23.96844543,   0.24421175])

In [13]:
model.intercept_

464.5628108859039

In [16]:
y_new = model.coef_[0]*1 + model.coef_[1]*1 + model.coef_[2]*4177+model.intercept_
y_new

1438.1235879014873

In [22]:
model = LinearRegression()
model.fit(data[['Brain Weight(grams)', 'Age Range', 'Head Size(cm^3)']], data.Gender)


LinearRegression()

In [24]:
model.predict([[1438,1,4177]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1.1186542])

In [25]:
model.predict([[1110,2,3214]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1.71215204])

In [26]:
model.predict([[1530,1,4512]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.87382057])

In [28]:
model.predict([[1170,2,3352]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1.59411376])